# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermodel',
            name='email',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
