# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_careermodel_describe_yourself'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermodel',
            name='Applying_For',
            field=models.CharField(choices=[('Medicalwriting', 'Medical Writing'), ('Assignmentwriting', 'Assignment Writing'), ('TechnicalWriting ', ' Technical Writing '), ('ResearchProjectWriting', ' Research Project Writing'), ('Dissertation Writing', 'Dissertation Writing')], default=' ', max_length=254),
        ),
    ]
