# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicename', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Point1', models.CharField(max_length=50)),
                ('Point2', models.CharField(max_length=50)),
                ('Point3', models.CharField(max_length=50)),
                ('Point4', models.CharField(max_length=50)),
                ('Point5', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
