# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Point1',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Point2',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Point3',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Point4',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Point5',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Servicename',
            field=models.CharField(max_length=100),
        ),
    ]
