# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180220_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='Description1',
            field=models.CharField(default='Description of above service', max_length=500),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='Description2',
            field=models.CharField(default='Description of above service', max_length=500),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='Description3',
            field=models.CharField(default='Description of above service', max_length=500),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='Description4',
            field=models.CharField(default='Description of above service', max_length=500),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='Description5',
            field=models.CharField(default='Description of above service', max_length=500),
        ),
    ]
