# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='image_big',
            field=models.ImageField(null=True, upload_to='service/big'),
        ),
    ]
