# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicemodel_image_big'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='Description5',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='Point5',
        ),
    ]
