# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180308_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='description_long',
            field=models.CharField(default='IT should be long description', max_length=3000),
        ),
    ]
