# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordernow', '0005_auto_20180302_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Academic_Level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('College', 'College'), ('University', ' University'), ('Master', 'Master'), ('PhD', ' PhD')], default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Number_of_Pages',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Phone_Number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Sources',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Subject',
            field=models.CharField(blank=True, choices=[('Art & Humanities', 'Art & Humanities'), ('Anthropology', ' Anthropology'), ('Archaeology', 'Archaeology'), ('Culture', ' Culture'), ('English', 'English'), ('Ethics', ' Ethics'), ('History and Anthropology', 'History and Anthropology'), ('Linguistics', ' Linguistics'), ('Literature', 'Literature'), ('Music', ' Music'), ('Psychology', 'Psychology'), ('Religion and Theology', ' Religion and Theology'), ('Visual Arts and Film Studies', 'Visual Arts and Film Studies'), ('Gender & Sexual Studies', ' Gender & Sexual Studies'), ('Geography', 'Geography'), ('Human Resources (HR)', ' Human Resources (HR)'), ('International Relations', 'International Relations'), ('Journalism, mass media and communication', ' Journalism, mass media and communicatio'), ('Political Science', 'Political Science'), ('Philosophy', ' Philosophy'), ('Sociology', 'Sociology'), ('Sciences', ' Sciences'), ('Astronomy', 'Astronomy'), ('Biology', ' Biology'), ('Chemistry', ' Chemistry'), ('Earth and Space Sciences', 'Earth and Space Sciences'), ('Mathematics', ' Mathematics'), ('Microbiology', 'Microbiology'), ('Physics', ' Physics'), ('Statistics', 'Statistics'), ('Information Technology', ' Information Technology'), ('Computer Sciences and Information Technology', 'Computer Sciences and Information Technology'), ('Logic and Programming', ' Logic and Programming'), ('Systems Science', 'Systems Science'), ('Applied Sciences', ' Applied Sciences'), ('Agriculture', 'Agriculture'), ('Architecture', ' Architecture'), ('Design and Technology', 'Design and Technology'), ('Education', ' Education'), ('Engineering and Construction', 'Engineering and Construction'), ('Environmental Studies', ' Environmental Studies'), ('Family and Consumer Science', 'Family and Consumer Science'), ('Health Sciences and Medicine', ' Health Sciences and Medicine'), ('Military Sciences', 'Military Sciences'), ('Healthcare and Nursing', ' Healthcare and Nursing'), ('Economics', 'Economics'), ('Business', ' Business'), ('E-commerce', 'E-commerce'), ('Finance and Accounting', ' Finance and Accounting'), ('Logistics', 'Logistics'), ('Macro & Micro Economics', ' Macro & Micro Economics'), ('Management', 'Management'), ('Tourism', ' Tourism'), ('Marketing', 'Marketing'), ('Law and International Law', ' Law and International Law'), ('Law and International Law', 'Law and International Law')], default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Type_of_Paper',
            field=models.CharField(blank=True, choices=[('Essay (Any Type)', 'Essay (Any Type)'), ('Research Paper', 'Research Paper'), ('Course Work', ' Course Work'), ('Team Paper', 'Team Paper'), ('Case Study', 'Case Study'), ('Book Review', 'Book Review'), ('Movie Review', 'Movie Review'), ('Annotated Bibliography', ' Annotated Bibliography'), ('Article', 'Article'), ('Assignment', 'Assignment'), ('Dissertation', 'Dissertation'), ('Lab Report', 'Lab Report'), ('Math Problem', ' Math Problem'), ('Speech', 'Speech'), ('Statistics Report', 'Statistics Report')], default=' ', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='spacing',
            field=models.CharField(blank=True, choices=[('Single_Space', 'Single Space'), ('Double_Space', 'Double Space')], default=' ', max_length=15, null=True),
        ),
    ]
