# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordernow', '0008_auto_20180306_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='Have_a_Budget',
        ),
    ]
