# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordernow', '0010_auto_20180505_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
    ]
