# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
