# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_auto_20180217_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
