# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20180217_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
