# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_auto_20180219_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='blog/', width_field='width'),
        ),
    ]
