# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0013_auto_20180220_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.CharField(blank=True, max_length=5999, null=True),
        ),
    ]
