# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0015_auto_20180221_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
