# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0016_auto_20180221_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='authorname',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
