# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0017_blogmodel_authorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='authorname',
            field=models.CharField(default='Divya', max_length=25),
        ),
    ]
