# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='content',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
