# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_samplemodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
