# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_samplemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='category',
            field=models.CharField(choices=[('contentwriting', 'Content Writing'), ('webdevelopment', 'Web Development'), ('graphicsdesigning', ' Graphics Designing'), ('Architecturedesigning', ' Architecture Designing'), ('Assignment Writing', 'Assignment Writing')], default='Content Writing', max_length=50),
        ),
    ]
